routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\TransactionHeaderController;
use App\Http\Controllers\TransactionDetailController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/dashboard', function () {
    return redirect('/');
})->middleware(['auth']);

require __DIR__.'/auth.php';


Route::resource('products', ProductController::class);
Route::resource('transactionheaders', TransactionHeaderController::class);
Route::resource('transactiondetails', TransactionDetailController::class);
Route::resource('carts', CartController::class);

Route::get('/', [HomeController::class, 'index']);
Route::get('view-cart', [CartController::class, 'cart'])->name('cart');
Route::get('add-to-cart/{id}', [CartController::class, 'addToCart'])->name('add.to.cart');
Route::patch('update-cart', [CartController::class, 'update'])->name('update.cart');
Route::delete('remove-from-cart', [CartController::class, 'remove'])->name('remove.from.cart');
Route::post('checkout-cart', [CartController::class, 'checkoutCart'])->name('checkout.cart');

Route::get('transactiondetails/show/{document_number}', [TransactionDetailController::class, 'getByDocNum']);

app/Models/TransactionHeader.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TransactionHeader extends Model
{
    use HasFactory;
    protected $fillable = [
        'document_code', 
        'document_number', 
        'user', 
        'total', 
        'date'
    ];
}

app/Http/Controllers/TransactionHeaderController.php
<?php

namespace App\Http\Controllers;

use App\Models\TransactionHeader;
use Illuminate\Http\Request;

class TransactionHeaderController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $products = TransactionHeader::latest()->paginate(5);
    
        return view('transactionheader.index',compact('products'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\TransactionHeader  $transactionHeader
     * @return \Illuminate\Http\Response
     */
    public function show(TransactionHeader $transactionHeader)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\TransactionHeader  $transactionHeader
     * @return \Illuminate\Http\Response
     */
    public function edit(TransactionHeader $transactionHeader)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\TransactionHeader  $transactionHeader
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, TransactionHeader $transactionHeader)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\TransactionHeader  $transactionHeader
     * @return \Illuminate\Http\Response
     */
    public function destroy(TransactionHeader $transactionHeader)
    {
        //
    }
}

resources/views/transactionheader/index.blade.php
@extends('layouts.app')

@section('title', 'Products')

@section('content')

<div class="container-fluid">
  <div class="row">
  	<div class="col-md-12 ">
	    @if ($message = Session::get('success'))
        <div class="alert alert-success" role="alert">
            <p>{{ $message }}</p>
        </div>
    	@endif
  		<a class="btn btn-primary float-left" href="{{ route('products.create') }}"><i class="material-icons">add</i> Create New @yield('title')</a>
  	</div>
    <div class="col-md-12">
      <div class="card">
        <div class="card-header card-header-success card-header-icon">
          <div class="card-icon">
            <i class="material-icons">face</i>
          </div>
          <h4 class="card-title">@yield('title') Data</h4>
        </div>
        <div class="card-body">
          <div class="toolbar">
            <!--        Here you can write extra buttons/actions for the toolbar              -->
          </div>
          <div class="material-datatables">
            <table id="datatables" class="table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
              <thead>
                <tr>
                    <th>Document Code</th>
                    <th>Document Number</th>
                    <th>User</th>
                    <th>Total</th>
                    <th>Date</th>
                    <th class="disabled-sorting text-right">&nbsp;</th>
                </tr>
              </thead>
              <tfoot>
                <tr>
                <th>Document Code</th>
                    <th>Document Number</th>
                    <th>User</th>
                    <th>Total</th>
                    <th>Date</th>
                    <th class="text-right">&nbsp;</th>
                </tr>
              </tfoot>
              <tbody>
              	@foreach ($products as $product)
                <tr>
                  <td>{{$product->document_code}}</td>
                  <td>{{$product->document_number}}</td>
                  <td>{{$product->user}}</td>
                  <td>{{$product->total}}</td>
                  <td>{{$product->date}}</td>
                  <td class="text-right">
                    <a href="{{route('transactiondetails.show', $product->document_number)}}" class="btn btn-link btn-info btn-just-icon like"><i class="material-icons">search</i></a>
                    <!-- <a href="{{route('products.edit', $product->id)}}" class="btn btn-link btn-warning btn-just-icon edit"><i class="material-icons">edit</i></a> -->
                    <!-- <a href="#" class="btn btn-link btn-danger btn-just-icon remove"><i class="material-icons">remove_circle</i></a> -->
                  </td>
                </tr>
                @endforeach
              </tbody>
            </table>
          </div>
        </div>
        <!-- end content-->
      </div>
      <!--  end card  -->
    </div>
    <!-- end col-md-12 -->
  </div>
  <!-- end row -->
</div>

@endsection

@section('jspage')

<script>
    $(document).ready(function() {
      $('#datatables').DataTable({
        "pagingType": "full_numbers",
        "lengthMenu": [
          [10, 25, 50, -1],
          [10, 25, 50, "All"]
        ],
        responsive: true,
        language: {
          search: "_INPUT_",
          searchPlaceholder: "Search records",
        }
      });

      var table = $('#datatable').DataTable();

      // Edit record
      table.on('click', '.edit', function() {
        $tr = $(this).closest('tr');
        var data = table.row($tr).data();
        alert('You press on Row: ' + data[0] + ' ' + data[1] + ' ' + data[2] + '\'s row.');
      });

      // Delete a record
      table.on('click', '.remove', function(e) {
        $tr = $(this).closest('tr');
        table.row($tr).remove().draw();
        e.preventDefault();
      });

      //Like record
      table.on('click', '.like', function() {
        alert('You clicked on Like button');
      });
    });
</script>
@endsection