routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\TransactionHeaderController;
use App\Http\Controllers\TransactionDetailController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/dashboard', function () {
    return redirect('/');
})->middleware(['auth']);

require __DIR__.'/auth.php';


Route::resource('products', ProductController::class);
Route::resource('transactionheaders', TransactionHeaderController::class);
Route::resource('transactiondetails', TransactionDetailController::class);
Route::resource('carts', CartController::class);

Route::get('/', [HomeController::class, 'index']);
Route::get('view-cart', [CartController::class, 'cart'])->name('cart');
Route::get('add-to-cart/{id}', [CartController::class, 'addToCart'])->name('add.to.cart');
Route::patch('update-cart', [CartController::class, 'update'])->name('update.cart');
Route::delete('remove-from-cart', [CartController::class, 'remove'])->name('remove.from.cart');
Route::post('checkout-cart', [CartController::class, 'checkoutCart'])->name('checkout.cart');

Route::get('transactiondetails/show/{document_number}', [TransactionDetailController::class, 'getByDocNum']);

app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\TransactionHeader;
use App\Models\TransactionDetail;
use Illuminate\Support\Facades\Auth;

class CartController extends Controller
{
    //
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {

        $products = Product::all();
        return view('carts.productlist', compact('products'));
    }

    public function cart(){
        return view('carts.cart');
    }

    public function addToCart($id){
        $product = Product::findOrFail($id);

        $cart = session()->get('cart', []);
        // echo "<pre>";print_r($cart);exit();
        if(isset($cart[$id])){
            $cart[$id]['qty']++;
        }else{
            $cart[$id] = [
                "product_name" => $product->product_name,
                "qty" => 1,
                "price" => $product->price,
            ];
        }
        session()->put('cart', $cart);
        return redirect()->back()->with('success', 'Product added to Cart successfully');
    }

    public function update(Request $request)
    {
        
        if($request->id && $request->qty){
            $cart = session()->get('cart');
            $cart[$request->id]["qty"] = $request->qty;
            session()->put('cart', $cart);
            session()->flash('success', 'Cart updated successfully');
        }
    }

    public function remove(Request $request)
    {
        if($request->id) {
            $cart = session()->get('cart');
            if(isset($cart[$request->id])) {
                unset($cart[$request->id]);
                session()->put('cart', $cart);
            }
            session()->flash('success', 'Product removed successfully');
        }
    }

    public function checkoutCart(Request $request){
        if($request->data){
            $head = TransactionHeader::latest()->first();
            if($head){
                $docnum = intval($head->document_number);
                $newdocnum = sprintf('%08d', $docnum + 1);
            }else{
                $newdocnum = sprintf('%08d', 1);
            }
            TransactionHeader::create([
                'document_code' => 'TRX',
                'document_number' => $newdocnum,
                'user' => Auth::user()->email,
                'total' => $request->total,
                'date' => date('Y-m-d H:i:s')
            ]);
            $data = $request->data;
            foreach($data as $d){
                $product = Product::findOrFail($d[0]);
                TransactionDetail::create([
                    'document_code' => 'TRX',
                    'document_number' => $newdocnum,
                    'product_code' => $product->product_code,
                    'price' => $product->price,
                    'quantity' => $d[1],
                    'unit' => $product->unit,
                    'sub_total' => $product->price * $d[1],
                    'currency' => $product->currency
                ]);

                if($d[0]) {
                    $cart = session()->get('cart');
                    if(isset($cart[$d[0]])) {
                        unset($cart[$d[0]]);
                        session()->put('cart', $cart);
                    }
                }
            }
            session()->flash('success', 'Product removed successfully');

            
        }
    }

}

resources/views/carts/cart.blade.php
@extends('layouts.app')

@section('title', 'Cart')

@section('content')

<div class="container-fluid">
  <div class="row">
  	<div class="col-md-12 ">
	    @if ($message = Session::get('success'))
        <div class="alert alert-success" role="alert">
            <p>{{ $message }}</p>
        </div>
    	@endif
  	</div>
    <div class="col-md-12">
      <div class="card">
        <div class="card-header card-header-success card-header-icon">
          <div class="card-icon">
            <i class="material-icons">face</i>
          </div>
          <h4 class="card-title">@yield('title')</h4>
        </div>
        <div class="card-body">
          <div class="toolbar">
            <!--        Here you can write extra buttons/actions for the toolbar              -->
          </div>
          <div class="material-datatables">
            <table class="table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
              <thead>
                <tr>
                    <th>Product Name</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Sub Total</th>
                    <th>&nbsp;</th>
                </tr>
              </thead>
              <tbody class="cart-data">
              @php $total = 0 @endphp
              @if(session('cart'))
                  @foreach(session('cart') as $id => $details)
                      @php $total += $details['price'] * $details['qty'] @endphp
                      <tr data-id="{{ $id }}">
                        <td><a href="{{route('products.show', $id)}}">{{$details['product_name']}}</a></td>
                        <td>{{$details['price']}}</td>
                        <td><input type="number" value="{{ $details['qty'] }}" class="form-control qty update-cart" /></td>
                        <td class="text-right">{{ $details['price'] * $details['qty'] }}</td>
                        <td class="text-right">
                        <button class="btn btn-danger btn-sm remove-from-cart">Remove</button>
                          <!-- <a href="#" class="btn btn-link btn-danger btn-just-icon remove"><i class="material-icons">remove_circle</i></a> -->
                        </td>
                      </tr>
                  @endforeach
                @else
                  <tr>
                    <td colspan="5">Cart Empty</td>
                  </tr>
                @endif
              </tbody>
              <tfoot>
                <tr>
                  <td colspan="4" class="text-right">Total: {{$total}}</td>
                  <td class="text-right"><button class="btn btn-primary checkout-cart">Confirm</button></td>
                </tr>
              </tfoot>
            </table>
          </div>
        </div>
        <!-- end content-->
      </div>
      <!--  end card  -->
    </div>
    <!-- end col-md-12 -->
  </div>
  <!-- end row -->
</div>

@endsection

@section('jspage')

<script>
  $(".update-cart").change(function (e) {
        e.preventDefault();
  
        var ele = $(this);
  
        $.ajax({
            url: "{{ route('update.cart') }}",
            method: "patch",
            data: {
                _token: '{{ csrf_token() }}', 
                id: ele.parents("tr").attr("data-id"), 
                qty: ele.parents("tr").find(".qty").val()
            },
            success: function (response) {
               window.location.reload();

            }
        });
    });
  
    $(".remove-from-cart").click(function (e) {
        e.preventDefault();
  
        var ele = $(this);
  
        if(confirm("Are you sure want to remove?")) {
            $.ajax({
                url: '{{ route('remove.from.cart') }}',
                method: "DELETE",
                data: {
                    _token: '{{ csrf_token() }}', 
                    id: ele.parents("tr").attr("data-id")
                },
                success: function (response) {
                    window.location.reload();
                }
            });
        }
    });

    $(".checkout-cart").click(function (e) {
        e.preventDefault();
        var arr = [];
        $('.cart-data tr').each(function(i){
          var item = [];
          var id = $(this).attr("data-id");
          var qty = $(this).find(".qty").val();
          // console.log($id);
          item = [id, qty];
          arr.push(item);
        });
        var ele = $(this);
        if(confirm("Are you sure?")) {
          $.ajax({
              url: "{{ route('checkout.cart') }}",
              method: "post",
              data: {
                  _token: '{{ csrf_token() }}', 
                  data: arr,
                  total: "{{$total}}",
              },
              success: function (response) {
                 window.location.reload();

              }
          });
        }
    });
</script>
@endsection

resources/views/carts/productlist.blade.php
@extends('layouts.app')

@section('title', 'Product List')

@section('content')

<div class="container-fluid">
  <div class="row">
  	<div class="col-md-12 ">
	    @if ($message = Session::get('success'))
        <div class="alert alert-success" role="alert">
            <p>{{ $message }}</p>
        </div>
    	@endif
  	</div>
    <div class="col-md-12">
      <div class="card">
        <div class="card-header card-header-success card-header-icon">
          <div class="card-icon">
            <i class="material-icons">face</i>
          </div>
          <h4 class="card-title">@yield('title')</h4>
        </div>
        <div class="card-body">
          <div class="toolbar">
            <!--        Here you can write extra buttons/actions for the toolbar              -->
          </div>
          <div class="material-datatables">
            <table id="datatables" class="table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
              <thead>
                <tr>
                    <th>Product Code</th>
                    <th>Product Name</th>
                    <th>Price</th>
                    <th>Currency</th>
                    <th>Discount</th>
                    <th>Dimension</th>
                    <th>Unit</th>
                    <th class="disabled-sorting text-right">&nbsp;</th>
                </tr>
              </thead>
              <tfoot>
                <tr>
                    <th>Product Code</th>
                    <th>Product Name</th>
                    <th>Price</th>
                    <th>Currency</th>
                    <th>Discount</th>
                    <th>Dimension</th>
                    <th>Unit</th>
                    <th class="text-right">&nbsp;</th>
                </tr>
              </tfoot>
              <tbody>
              	@foreach ($products as $product)
                <tr>
                  <td>{{$product->product_code}}</td>
                  <td>{{$product->product_name}}</td>
                  <td>{{$product->price}}</td>
                  <td>{{$product->currency}}</td>
                  <td>{{$product->discount}}</td>
                  <td>{{$product->dimension}}</td>
                  <td>{{$product->unit}}</td>
                  <td class="text-right">
                    <a href="{{route('products.show', $product->id)}}" class="btn btn-link btn-info btn-just-icon like"><i class="material-icons">search</i></a>
                    <a href="{{ route('add.to.cart', $product->id) }}" class="btn btn-info"><i class="material-icons">add_shopping_cart</i> Add to Cart</a>
                    <!-- <a href="#" class="btn btn-link btn-danger btn-just-icon remove"><i class="material-icons">remove_circle</i></a> -->
                  </td>
                </tr>
                @endforeach
              </tbody>
            </table>
          </div>
        </div>
        <!-- end content-->
      </div>
      <!--  end card  -->
    </div>
    <!-- end col-md-12 -->
  </div>
  <!-- end row -->
</div>

@endsection

@section('jspage')

<script>
    $(document).ready(function() {
      $('#datatables').DataTable({
        "pagingType": "full_numbers",
        "lengthMenu": [
          [10, 25, 50, -1],
          [10, 25, 50, "All"]
        ],
        responsive: true,
        language: {
          search: "_INPUT_",
          searchPlaceholder: "Search records",
        }
      });

      var table = $('#datatable').DataTable();

      // Edit record
      table.on('click', '.edit', function() {
        $tr = $(this).closest('tr');
        var data = table.row($tr).data();
        alert('You press on Row: ' + data[0] + ' ' + data[1] + ' ' + data[2] + '\'s row.');
      });

      // Delete a record
      table.on('click', '.remove', function(e) {
        $tr = $(this).closest('tr');
        table.row($tr).remove().draw();
        e.preventDefault();
      });

      //Like record
      table.on('click', '.like', function() {
        alert('You clicked on Like button');
      });
    });
</script>
@endsection