routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\TransactionHeaderController;
use App\Http\Controllers\TransactionDetailController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/dashboard', function () {
    return redirect('/');
})->middleware(['auth']);

require __DIR__.'/auth.php';


Route::resource('products', ProductController::class);
Route::resource('transactionheaders', TransactionHeaderController::class);
Route::resource('transactiondetails', TransactionDetailController::class);
Route::resource('carts', CartController::class);

Route::get('/', [HomeController::class, 'index']);
Route::get('view-cart', [CartController::class, 'cart'])->name('cart');
Route::get('add-to-cart/{id}', [CartController::class, 'addToCart'])->name('add.to.cart');
Route::patch('update-cart', [CartController::class, 'update'])->name('update.cart');
Route::delete('remove-from-cart', [CartController::class, 'remove'])->name('remove.from.cart');
Route::post('checkout-cart', [CartController::class, 'checkoutCart'])->name('checkout.cart');

Route::get('transactiondetails/show/{document_number}', [TransactionDetailController::class, 'getByDocNum']);

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    protected $fillable = [
        'product_code', 
        'product_name', 
        'price', 
        'currency', 
        'discount', 
        'dimension', 
        'unit', 
    ];
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::latest()->paginate(5);
    
        return view('products.index',compact('products'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'product_code'      => 'required',
            'product_name'      => 'required',
            'price'             => 'required',
            'currency'          => 'required',
            'discount'          => 'required',
            'dimension'         => 'required',
            'unit'              => 'required'
        ]);

        Product::create($request->all());

        return redirect()->route('products.index')->with('success', 'Product created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('products.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('products.edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $request->validate([
            'product_code'      => 'required',
            'product_name'      => 'required',
            'price'             => 'required',
            'currency'          => 'required',
            'discount'          => 'required',
            'dimension'         => 'required',
            'unit'              => 'required'
        ]);

        $product->update($request->all());

        return redirect()->route('products.index')->with('success', 'Product updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->delete();

        return redirect()->route('products.index')->with('success', 'Product deleted successfully.');
    }

    
}

resources/views/products/create.blade.php
@extends('layouts.app')
@section('title', 'Create New Product')
@section('content')

<div class="row">
    <div class="col-md-12">
        <div class="float-right">
            <a class="btn btn-primary" href="{{ route('products.index') }}"><i class="material-icons">chevron_left</i> Back</a>
        </div>
    </div>
</div>

   

@if ($errors->any())
    <div class="alert alert-danger" role="alert">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif



<div class="col-md-12">
    <div class="card ">
    <form action="{{ route('products.store') }}" method="POST" class="form-horizontal">
        {{ csrf_field() }}
        <div class="card-header card-header-rose card-header-text">
          <div class="card-text">
            <h4 class="card-title">New Product Form</h4>
          </div>
        </div>
        <div class="card-body ">
            <div class="row">
                <label class="col-sm-2 col-form-label">Product Code</label>
                <div class="col-sm-10">
                    <div class="form-group bmd-form-group">
                      <input type="text" class="form-control" name="product_code">
                    </div>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-2 col-form-label">Product Name</label>
                <div class="col-sm-10">
                    <div class="form-group bmd-form-group">
                      <input type="text" class="form-control" name="product_name">
                    </div>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-2 col-form-label">Price</label>
                <div class="col-sm-10">
                    <div class="form-group bmd-form-group">
                        <input type="text" class="form-control" name="price">
                    </div>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-2 col-form-label">Currency</label>
                <div class="col-sm-10">
                    <div class="form-group bmd-form-group">
                        <input type="text" class="form-control" name="currency">
                    </div>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-2 col-form-label">Discount</label>
                <div class="col-sm-10">
                    <div class="form-group bmd-form-group">
                        <input type="text" class="form-control" name="discount">
                    </div>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-2 col-form-label">Dimension</label>
                <div class="col-sm-10">
                    <div class="form-group bmd-form-group">
                        <input type="text" class="form-control" name="dimension">
                    </div>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-2 col-form-label">Unit</label>
                <div class="col-sm-10">
                    <div class="form-group bmd-form-group">
                        <input type="text" class="form-control" name="unit">
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer ">
            <button type="submit" class="btn btn-fill btn-primary">Submit</button>
        </div>
    </form>
    </div>
</div>

@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')
@section('title', 'Edit Product')
@section('content')

<div class="row">
    <div class="col-md-12">
        <div class="float-right">
            <a class="btn btn-primary" href="{{ route('products.index') }}"><i class="material-icons">chevron_left</i> Back</a>
        </div>
    </div>
</div>

   

@if ($errors->any())
    <div class="alert alert-danger" role="alert">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif



<div class="col-md-12">
    <div class="card ">
    <form action="{{ route('products.update', $product->id) }}" method="POST" class="form-horizontal">
        {{ csrf_field() }}
        {{method_field('PUT')}}
        <div class="card-header card-header-rose card-header-text">
          <div class="card-text">
            <h4 class="card-title">Edit Product Form</h4>
          </div>
        </div>
        <div class="card-body ">
            <div class="row">
                <label class="col-sm-2 col-form-label">Name</label>
                <div class="col-sm-10">
                    <div class="form-group bmd-form-group">
                      <input type="text" class="form-control" name="name" value="{{$product->name}}">
                    </div>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-2 col-form-label">Join Date</label>
                <div class="col-sm-10">
                    <div class="form-group bmd-form-group">
                        <input type="text" class="form-control" name="detail" value="{{$product->detail}}">
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer ">
            <button type="submit" class="btn btn-fill btn-primary">Submit</button>
        </div>
    </form>
    </div>
</div>

@endsection

resources/views/products/index.blade.php
@extends('layouts.app')

@section('title', 'Products')

@section('content')

<div class="container-fluid">
  <div class="row">
  	<div class="col-md-12 ">
	    @if ($message = Session::get('success'))
        <div class="alert alert-success" role="alert">
            <p>{{ $message }}</p>
        </div>
    	@endif
  		<a class="btn btn-primary float-left" href="{{ route('products.create') }}"><i class="material-icons">add</i> Create New @yield('title')</a>
  	</div>
    <div class="col-md-12">
      <div class="card">
        <div class="card-header card-header-success card-header-icon">
          <div class="card-icon">
            <i class="material-icons">face</i>
          </div>
          <h4 class="card-title">@yield('title') Data</h4>
        </div>
        <div class="card-body">
          <div class="toolbar">
            <!--        Here you can write extra buttons/actions for the toolbar              -->
          </div>
          <div class="material-datatables">
            <table id="datatables" class="table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
              <thead>
                <tr>
                    <th>Product Code</th>
                    <th>Product Name</th>
                    <th>Price</th>
                    <th>Currency</th>
                    <th>Discount</th>
                    <th>Dimension</th>
                    <th>Unit</th>
                    <th class="disabled-sorting text-right">&nbsp;</th>
                </tr>
              </thead>
              <tfoot>
                <tr>
                    <th>Product Code</th>
                    <th>Product Name</th>
                    <th>Price</th>
                    <th>Currency</th>
                    <th>Discount</th>
                    <th>Dimension</th>
                    <th>Unit</th>
                    <th class="text-right">&nbsp;</th>
                </tr>
              </tfoot>
              <tbody>
              	@foreach ($products as $product)
                <tr>
                  <td>{{$product->product_code}}</td>
                  <td>{{$product->product_name}}</td>
                  <td>{{$product->price}}</td>
                  <td>{{$product->currency}}</td>
                  <td>{{$product->discount}}</td>
                  <td>{{$product->dimension}}</td>
                  <td>{{$product->unit}}</td>
                  <td class="text-right">
                    <a href="{{route('products.show', $product->id)}}" class="btn btn-link btn-info btn-just-icon like"><i class="material-icons">search</i></a>
                    <a href="{{route('products.edit', $product->id)}}" class="btn btn-link btn-warning btn-just-icon edit"><i class="material-icons">edit</i></a>
                    <!-- <a href="#" class="btn btn-link btn-danger btn-just-icon remove"><i class="material-icons">remove_circle</i></a> -->
                  </td>
                </tr>
                @endforeach
              </tbody>
            </table>
          </div>
        </div>
        <!-- end content-->
      </div>
      <!--  end card  -->
    </div>
    <!-- end col-md-12 -->
  </div>
  <!-- end row -->
</div>

@endsection

@section('jspage')

<script>
    $(document).ready(function() {
      $('#datatables').DataTable({
        "pagingType": "full_numbers",
        "lengthMenu": [
          [10, 25, 50, -1],
          [10, 25, 50, "All"]
        ],
        responsive: true,
        language: {
          search: "_INPUT_",
          searchPlaceholder: "Search records",
        }
      });

      var table = $('#datatable').DataTable();

      // Edit record
      table.on('click', '.edit', function() {
        $tr = $(this).closest('tr');
        var data = table.row($tr).data();
        alert('You press on Row: ' + data[0] + ' ' + data[1] + ' ' + data[2] + '\'s row.');
      });

      // Delete a record
      table.on('click', '.remove', function(e) {
        $tr = $(this).closest('tr');
        table.row($tr).remove().draw();
        e.preventDefault();
      });

      //Like record
      table.on('click', '.like', function() {
        alert('You clicked on Like button');
      });
    });
</script>
@endsection

resources/views/products/show.blade.php
@extends('layouts.app')
@section('title', 'Show Product')
@section('content')

<div class="row">
    <div class="col-md-12">
        <div class="float-right">
            <a class="btn btn-primary" href="{{ route('products.index') }}"><i class="material-icons">chevron_left</i> Back</a>
        </div>
    </div>
</div>

<div class="col-md-12">
    <div class="card ">
        <div class="card-header card-header-rose card-header-text">
          <div class="card-text">
            <h4 class="card-title">@yield('title', 'Show Data') Form</h4>
          </div>
        </div>
        <div class="card-body ">
            <div class="row">
                <label class="col-sm-2 col-form-label">Product Code</label>
                <div class="col-sm-10">
                    <div class="form-group bmd-form-group">
                      {{$product->product_code}}
                    </div>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-2 col-form-label">Product Name</label>
                <div class="col-sm-10">
                    <div class="form-group bmd-form-group">
                      {{$product->product_name}}
                    </div>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-2 col-form-label">Price</label>
                <div class="col-sm-10">
                    <div class="form-group bmd-form-group">
                      {{$product->price}}
                    </div>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-2 col-form-label">Currency</label>
                <div class="col-sm-10">
                    <div class="form-group bmd-form-group">
                      {{$product->currency}}
                    </div>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-2 col-form-label">Discount</label>
                <div class="col-sm-10">
                    <div class="form-group bmd-form-group">
                      {{$product->discount}}
                    </div>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-2 col-form-label">Dimension</label>
                <div class="col-sm-10">
                    <div class="form-group bmd-form-group">
                      {{$product->dimension}}
                    </div>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-2 col-form-label">Unit</label>
                <div class="col-sm-10">
                    <div class="form-group bmd-form-group">
                      {{$product->unit}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection